export const KEYWORDS_SEO = [
  'Abelardo',
  'Aqui',
  'Arroyo',
  'Abelardo Aqui',
  'Abelardo Aqui Arroyo',
  'frontend',
  'angular',
  'nextjs',
  'nestjs',
  'nodejs',
  'node',
  'developer',
  'leader',
  'mexican',
  'portfolio',
  'mx software solutions',
  'stefanini',
  'eon ignigting business'
]
