export const KEYWORDS_SEO = [
  'Abelardo',
  'Aqui',
  'Arroyo',
  'Abelardo Aqui',
  'Abelardo Aqui Arroyo',
  'developer',
  'dev',
  'desarrollador',
  'frontend-lead',
  'frontend',
  'angular',
  'nextjs',
  'nestjs',
  'nodejs',
  'node',
  'mongo',
  'developer',
  'leader',
  'mexican',
  'portfolio',
  'mx software solutions',
  'stefanini',
  'eon ignigting business',
  'central textilera',
  'scorce',
  'mexico',
  'tecabel',
  'ciudad de mexico',
  'mexico city'
]
